in main, call foo
	 in foo
		 in foo1
			 in foo2
aspect, throw 3
catch exception = 3
end of main
