in main, call foo
	 in foo
		 in foo1
			 in foo2
before call foo3, throw exception 3
catch exception 3 from calling foo2
	 end of foo
end of main
